  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/ssgdb
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql : true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true

  #springdoc / swagger setting
  springdoc:
    api-docs:
      path: /api-docs
      groups:
        enabled : true
        groups-order: ASC
        tags-sorter: alpha
        display-request-duration: true
        doc-expansion: none
      cashe:
        disabled: true
      model-and-view-allowed: true